name: Tflint
description: "Run TFLint in the specified directory"
inputs:
  folder_to_lint:
    description: The folder where to run TFLint
    required: true
    default: "."
  path_to_config:
    description: The path to the config file
    required: true
    default: ".tflint.hcl"
runs:
  using: "docker"
  image: "docker://sebastianneb/gcloud-terragrunt-deployer:v1.0.1"
  entrypoint: run_tflint.sh
  args:
    - ${{ inputs.folder_to_lint }}
    - ${{ inputs.path_to_config }}
