name: Docker Build
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - "*"
jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get current time
        uses: gerred/actions/current-time@master
        id: current-time
      - name: Docker Build
        uses: docker/build-push-action@v1
        with:
          repository: sebastianneb/gcloud-terragrunt-deployer
          tag_with_sha: true
          push: false
          build_args: CREATED="${{ steps.current-time.outputs.time }}",VERSION="$GITHUB_SHA",REVISION=$GITHUB_REF
