name: Docker Build
on: [push]

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Docker Build
        run: echo "Should build it"
      - name: List all available files within the directory
        run: ls -la
